services:
  db:
    command: '--default-time-zone "+00:00"'
    container_name: opc-db
    environment:
      - MARIADB_DATABASE=openprivatecloud
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb-pw
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb-pw
      - MARIADB_USER=opc
    image: mariadb
    networks:
      opcnet:
        ipv4_address: 10.1.0.2
    restart: always
    volumes:
      - ./dbdatadir:/var/lib/mysql:Z
      - ./dbimport:/docker-entrypoint-initdb.d/
      - ./certs/dbpw:/run/secrets/mariadb-pw

  backend:
    container_name: opc-backend
    depends_on:
      - db
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/OpenPrivateCloud/oidp-ca.crt
      - OPC_ALLOWED_ORIGINS=https://localhost:8079
      - OPC_DBHOST=10.1.0.2
      - OPC_DBUSER=opc
      - OPC_MASTER_KEYSTORE_PATH=/etc/OpenPrivateCloud/masterkey.json
      - OPC_OIDP_AUDIENCE=https://localhost:8078
      - OPC_OIDP_CLIENT_ID=YOUR_OIDP_CLIENT_ID
      - OPC_OIDP_CLIENT_SECRET=YOUR_OIDP_CLIENT_SECRET
      - OPC_OIDP_ENDPOINT=https://YOUR_OIDP_DOMAIN_NAME:3000
    image: ghcr.io/aczwink/openprivatecloud-backend
    network_mode: host
    restart: always
    volumes:
      - ./certs:/etc/OpenPrivateCloud:ro

  frontend:
    container_name: opc-frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443 #port inside container
      - OPC_BACKEND_URL=https://localhost:8078
      - OPC_CLIENT_ID=YOUR_OPC_CLIENT_ID
      - OPC_FRONTEND_BASEURL=https://localhost:8079
      - OPC_OIDP_ENDPOINT=localhost:3000
    image: ghcr.io/aczwink/openprivatecloud-frontend
    networks:
      opcnet:
        ipv4_address: 10.1.0.3
    ports:
      - "8079:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:ro
      
networks:
  opcnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/24
         gateway: 10.1.0.1
