name: Build docker images

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v3

    #setup build tools
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    #build acts-util-core
    - name: Checkout ACTS-Util repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/ACTS-Util
        path: actsutil

    - run: npm install
      working-directory: ./actsutil/core
    - run: npm run compile
      working-directory: ./actsutil/core
    - run: npm link
      working-directory: ./actsutil/core

    #build acts-util-node
    - run: npm link acts-util-core
      working-directory: ./actsutil/node
    - run: npm install
      working-directory: ./actsutil/node
    - run: npm run build
      working-directory: ./actsutil/node
    - run: npm link
      working-directory: ./actsutil/node


    #build common
    - run: npm install
      working-directory: ./common
    - run: npm run build
      working-directory: ./common
    - run: npm link
      working-directory: ./common

    #build backend
    - name: Linking backend dependencies
      run: npm link acts-util-core acts-util-node openprivatecloud-common
      working-directory: ./backend
    - run: npm install
      working-directory: ./backend
    - run: npm run build-release-package
      working-directory: ./backend

    #build frontend
    - run: npm install
      working-directory: ./frontend
    - run: npm run generate-api
      working-directory: ./frontend

    #publish images      
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/aczwink/openprivatecloud-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/aczwink/openprivatecloud-frontend:latest
